// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ProductionContext))]
    [Migration("20240715154551_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("WebApplication1.Models.ProductionPlanComplete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Friday")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Monday")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Saturday")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sunday")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Thursday")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tuesday")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wednesday")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ProductionPlansComplete");
                });

            modelBuilder.Entity("WebApplication1.Models.ProductionResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Friday")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Monday")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductionPlanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Saturday")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sunday")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Thursday")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tuesday")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wednesday")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ProductionResults");
                });
#pragma warning restore 612, 618
        }
    }
}
